# Only for editor support, meson does it's own thing
[package]
name = "render"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies.windows]
version = "0.60.0"
features = ["Win32_UI_WindowsAndMessaging"]
