[package]
name = "audio"
version = "1.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
kira = "0.10.4"
symphonia = "0.5.4" # re-enable default codecs, specifically adpcm
